### ISSUE TITLE
Improve documentation for version constraints

### ISSUE THREAD

**Issue by mietek** [mietek/halcyon-website#1]
- [ ] Clarify using [`HALCYON_CONSTRAINTS`](https://halcyon.sh/reference/#halcyon_constraints) or including a `cabal.config` file is optional.
- [ ] Explain the way Halcyon uses `cabal.config` files. (https://github.com/mietek/halcyon/issues/40#issuecomment-74541463)
- [x] Clarify setting [`HALCYON_IGNORE_ALL_CONSTRAINTS`](https://halcyon.sh/reference/#halcyon_ignore_all_constraints) to `1` does not cause version constraints included in the `build-depends` field of a Cabal package description file to be ignored. (https://github.com/mietek/halcyon/issues/48#issuecomment-75455191)
- [ ] Prepare for upcoming Stackage-related changes. (https://github.com/mietek/halcyon/issues/41)
